In [1]:
%matplotlib inline
import numpy as np

In [2]:
np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [8]:
a = np.ones((4, 4), dtype = int) # OR dtype = np.int8
a[2, 3] = 2
a[3, 1] = 6
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 6, 1, 1]])

In [7]:
a = np.diag(np.arange(2, 7, dtype = float), k = -1)[:, 0:-1]
a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.,  0.],
       [ 0.,  3.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  6.]])

In [11]:
a = np.array([[4, 3], [2, 1]])
b = np.tile(a, (2, 3)) # 2 rows * 3 columns tile matrix with each element (tile) being "a"
b

array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

In [13]:
len(b)

4

In [15]:
np.shape(b)

(4, 6)

In [16]:
b.dtype

dtype('int64')